sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mostafa448/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mostafa448/docker-react npm run test -- --coverage # -- --coverage to exit npm run test automatically

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3" # the region you choose
  app: "docker-react" # a name that you setup in aws
  env: "Dockerreact-env-1" # a name that revere as the environment
  bucket_name: "elasticbeanstalk-eu-west-3-661172005059"
  bucket_path: "docker-react" # the name same as app names
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
